//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreSample.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int IdOrder { get; set; }
        public int BookId { get; set; }
        public System.DateTime OrderPlacedAtUtc { get; set; }
        public int Quantity { get; set; }
        public decimal TotalPrice { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string TelephoneNumber { get; set; }
        public string HouseNumber { get; set; }
        public string PostCode { get; set; }
        public string CreditCardNumber { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
