SET IDENTITY_INSERT [dbo].[Books] ON
INSERT INTO [dbo].[Books] ([IdBook], [Title], [Author], [Description], [Price]) VALUES (1, N'Alan Turing: The Enigma', N'Andrew Hodges', N'Alan Turing was the mathematician whose cipher-cracking transformed the Second World War. Taken on by British Intelligence in 1938, as a shy young Cambridge don, he combined brilliant logic with a flair for engineering. In 1940 his machines were breaking the Enigma-enciphered messages of Nazi Germany’s air force. He then headed the penetration of the super-secure U-boat communications. 
', CAST(6.9900 AS Money))
INSERT INTO [dbo].[Books] ([IdBook], [Title], [Author], [Description], [Price]) VALUES (2, N'Python: Learn Python in One Day and Learn It Well. Python for Beginners with Hands-on Project.', N'Jamie Chan', N'Have you always wanted to learn computer programming but are afraid it''ll be too difficult for you? Or perhaps you know other programming languages but are interested in learning the Python language fast? ', CAST(7.7900 AS Money))
INSERT INTO [dbo].[Books] ([IdBook], [Title], [Author], [Description], [Price]) VALUES (3, N'Cracking the Coding Interview, 6th Edition: 189 Programming Questions and Solutions', N'Gayle Laakmann McDowell ', N'I am not a recruiter. I am a software engineer. And as such, I know what it''s like to be asked to whip up brilliant algorithms on the spot and then write flawless code on a whiteboard. I''ve been through this—as a candidate and as an interviewer.

Cracking the Coding Interview, 6th Edition is here to help you through this process, teaching you what you need to know and enabling you to perform at your very best. I''ve coached and interviewed hundreds of software engineers. The result is this book.', CAST(19.0200 AS Money))
INSERT INTO [dbo].[Books] ([IdBook], [Title], [Author], [Description], [Price]) VALUES (4, N'Rtfm: Red Team Field Manual ', N'Ben Clark', N'The Red Team Field Manual (RTFM) is a no fluff, but thorough reference guide for serious Red Team members who routinely find themselves on a mission without Google or the time to scan through a man page. The RTFM contains the basic syntax for commonly used Linux and Windows command line tools, but it also encapsulates unique use cases for powerful tools such as Python and Windows PowerShell. The RTFM will repeatedly save you time looking up the hard to remember Windows nuances such as Windows wmic and dsquery command line tools, key registry values, scheduled tasks syntax, startup locations and Windows scripting. More importantly, it should teach you some new red team techniques.', CAST(3.4600 AS Money))
INSERT INTO [dbo].[Books] ([IdBook], [Title], [Author], [Description], [Price]) VALUES (5, N'Get Coding! Learn HTML, CSS, & JavaScript & Build a Website, App, & Game ', N'Young Rewired State', N'Learn how to write code and then build your own website, app and game using HTML, CSS and JavaScript in this essential guide to coding for kids from expert organization Young Rewired State. Over 6 fun missions learn the basic concepts of coding or computer programming and help Professor Bairstone and Dr Day keep the Monk Diamond safe from dangerous jewel thieves. In bite-size chunks learn important real-life coding skills and become a technology star of the future. Young Rewired State is a global community that aims to get kids coding and turn them into the technology stars of the future.', CAST(3.9900 AS Money))
INSERT INTO [dbo].[Books] ([IdBook], [Title], [Author], [Description], [Price]) VALUES (6, N'Algorithms To Live By: The Computer Science of Human Decisions', N'Brian Christian', N'A fascinating exploration of how computer algorithms can be applied to our everyday lives.

What should we do, or leave undone, in a day or a lifetime?

Exploring how insights from computer algorithms can be applied to our everyday lives, ‘Algorithms To Live By’ helps to solve common decision-making problems and illuminate the workings of the human mind. When should you switch between different tasks, and how many tasks should you take on in the first place? How much messiness should you accept? What balance of new activities and familiar favourites is the most fulfilling? When computers face constraints of time and space, they too must untangle very human questions: how to have better hunches, when to leave things to chance, how to deal with overwhelming choices and how best to connect with others. And the solutions they’ve found have much to teach us.

Acclaimed author Brian Christian and cognitive scientist Tom Griffiths show how the algorithms developed for computers can be applied from finding your spouse to finding a parking spot, from organizing your inbox to understanding the workings of memory. Where you have a dilemma, they have a rule, and each fascinating algorithm turns the wisdom of computer science into strategies for human living.', CAST(13.6000 AS Money))
INSERT INTO [dbo].[Books] ([IdBook], [Title], [Author], [Description], [Price]) VALUES (7, N'Superintelligence: Paths, Dangers, Strategies', N'Nick Bostrom', N'The human brain has some capabilities that the brains of other animals lack. It is to these distinctive capabilities that our species owes its dominant position. Other animals have stronger muscles or sharper claws, but we have cleverer brains. 

If machine brains one day come to surpass human brains in general intelligence, then this new superintelligence could become very powerful. As the fate of the gorillas now depends more on us humans than on the gorillas themselves, so the fate of our species then would come to depend on the actions of the machine superintelligence. 

But we have one advantage: we get to make the first move. Will it be possible to construct a seed AI or otherwise to engineer initial conditions so as to make an intelligence explosion survivable? How could one achieve a controlled detonation? 

To get closer to an answer to this question, we must make our way through a fascinating landscape of topics and considerations. Read the book and learn about oracles, genies, singletons; about boxing methods, tripwires, and mind crime; about humanity''s cosmic endowment and differential technological development; indirect normativity, instrumental convergence, whole brain emulation and technology couplings; Malthusian economics and dystopian evolution; artificial intelligence, and biological cognitive enhancement, and collective intelligence. 

This profoundly ambitious and original book picks its way carefully through a vast tract of forbiddingly difficult intellectual terrain. Yet the writing is so lucid that it somehow makes it all seem easy. After an utterly engrossing journey that takes us to the frontiers of thinking about the human condition and the future of intelligent life, we find in Nick Bostrom''s work nothing less than a reconceptualization of the essential task of our time.', CAST(6.9900 AS Money))
INSERT INTO [dbo].[Books] ([IdBook], [Title], [Author], [Description], [Price]) VALUES (8, N'Python Programming for the Absolute Beginner ', N'Mike Dawson', N'If you are new to programming with Python and are looking for a solid introduction, this is the book for you. Developed by computer science instructors, books in the ""for the absolute beginner"" series teach the principles of programming through simple game creation. You will acquire the skills that you need for practical Python programming applications and will learn how these skills can be put to use in real-world scenarios. Throughout the chapters, you will find code samples that illustrate concepts presented. At the end of each chapter, you will find a complete game that demonstrates the key ideas in the chapter, a summary of the chapter, and a set of challenges that tests your newfound knowledge. By the time you finish this book, youll be well versed in Python and be able to apply the basic programming principles youve learned to the next programming language you tackle.', CAST(16.3100 AS Money))
INSERT INTO [dbo].[Books] ([IdBook], [Title], [Author], [Description], [Price]) VALUES (9, N'HTML & CSS: Design and Build Web Sites', N'Jon Duckett', N'Every day, more and more people want to learn some HTML and CSS. Joining the professional web designers and programmers are new audiences who need to know a little bit of code at work (update a content management system or e–commerce store) and those who want to make their personal blogs more attractive. Many books teaching HTML and CSS are dry and only written for those who want to become programmers, which is why this book takes an entirely new approach.

Introduces HTML and CSS in a way that makes them accessible to everyone―hobbyists, students, and professionals―and it’s full–color throughout
Utilizes information graphics and lifestyle photography to explain the topics in a simple way that is engaging
Boasts a unique structure that allows you to progress through the chapters from beginning to end or just dip into topics of particular interest at your leisure
This educational book is one that you will enjoy picking up, reading, then referring back to. It will make you wish other technical topics were presented in such a simple, attractive and engaging way!
', CAST(13.5900 AS Money))
INSERT INTO [dbo].[Books] ([IdBook], [Title], [Author], [Description], [Price]) VALUES (10, N'Clean Code: A Handbook of Agile Software Craftsmanship', N'Robert C. Martin', N'Even bad code can function. But if code isn’t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesn’t have to be that way. Noted software expert Robert C. Martin presents a revolutionary paradigm with Clean Code: A Handbook of Agile Software Craftsmanship . Martin has teamed up with his colleagues from Object Mentor to distill their best agile practice of cleaning code “on the fly” into a book that will instill within you the values of a software craftsman and make you a better programmer—but only if you work at it. What kind of work will you be doing? You’ll be reading code—lots of code. And you will be challenged to think about what’s right about that code, and what’s wrong with it. More importantly, you will be challenged to reassess your professional values and your commitment to your craft. Clean Code is divided into three parts. The first describes the principles, patterns, and practices of writing clean code. The second part consists of several case studies of increasing complexity. Each case study is an exercise in cleaning up code—of transforming a code base that has some problems into one that is sound and efficient. The third part is the payoff: a single chapter containing a list of heuristics and “smells” gathered while creating the case studies. The result is a knowledge base that describes the way we think when we write, read, and clean code. Readers will come away from this book understanding How to tell the difference between good and bad code How to write good code and how to transform bad code into good code How to create good names, good functions, good objects, and good classes How to format code for maximum readability How to implement complete error handling without obscuring code logic How to unit test and practice test-driven development This book is a must for any developer, software engineer, project manager, team lead, or systems analyst with an interest in producing better code.', CAST(16.9400 AS Money))
SET IDENTITY_INSERT [dbo].[Books] OFF
